version: "3.7"

services:
  dots_rosdevel:
    image: simonj23/dots_rosdevel:foxy
    build:
      context: ../
      dockerfile: docker/Dockerfile.rosdevel
    environment:
      - USER=dots 
    ports:
      - "8080:8080"
      - "8081:80"
      - "8082:5900"
      - "8085:8085"
    volumes:
      - ../:/home/dots/dots_system
    networks:
      - dots_network

networks:
  dots_network: